name: Build-Padavan-K2P

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
  schedule:
    - cron: "0 0 1,16 * *"

    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_URL: https://github.com/yer2018/Padavan-K2P
  TNAME: K2P
  KERNEL: 3.4
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
        
    - name: 最大化编译空间
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    
    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: 克隆源码
      working-directory: /workdir
      run: |
        git clone $REPO_URL --depth=1 rt-n56u
        ln -sf /workdir/rt-n56u $GITHUB_WORKSPACE/rt-n56u
        cd rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        [ -d "/workdir/rt-n56u/toolchain-mipsel/toolchain-3.4.x" ] && sudo ln -svf /workdir/rt-n56u/toolchain-mipsel/toolchain-3.4.x /toolchain-3.4.x
        df -hT /workdir
        echo "FILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV
    - name: 加载自定义配置
      run: |
        cd rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        #修改默认IP地址
        sed -i 's/192.168.2.1/10.10.10.1/g' ./user/shared/defaults.h
        sed -i 's/192.168.2.100/10.10.10.101/g' ./user/shared/defaults.h
        sed -i 's/192.168.2.244/10.10.10.199/g' ./user/shared/defaults.h
        
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SRELAY=y/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=y/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n/g' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XRAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NPC/d' .config
        sed -i '/CONFIG_FIRMWARE_WEBUI_HIDE_VPN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        ##内网穿透
        echo "CONFIG_FIRMWARE_INCLUDE_NPC=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config  #frpc
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #aliddns
        ##科学上网##
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config
        #echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config
        #echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=y" >> .config
        ##vpn
        #echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=y" >> .config
        #echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=y" >> .config
        #echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=y" >> .config
        #echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=y" >> .config
        
        ###############################################################################
        ##########
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        
        sed -i 's/\r//' .config
        
    - name: SSH connect to Actions
      uses: P3TERX/ssh2actions@main
      if: github.event.inputs.ssh == 'true'
      
    - name: 编译固件
      run: |
        cd rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0

    - name: 整理文件
      run: |
        df -Th /workdir
        mkdir /workdir/images
        cp rt-n56u/trunk/images/*.trx /workdir/images/K2P_${{ env.FILE_DATE }}.trx
        ls -lh /workdir/images/
        echo "PACKAGED_OUTPUTPATH=/workdir/images" >> $GITHUB_ENV

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      with:
        tag_name: Padavan-K2P_${{ env.FILE_DATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/K2P_${{ env.FILE_DATE }}.trx
        body: |
          首次使用建议全新刷写
          * 基本信息
          IP: 10.10.10.1
          账户: admin
          密码: admin

    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 7
        delete_tags : true
